version: "2"

services:
  web:
    image: nginx:latest
    ports:
    - '80:80'
    volumes:
      - .:/code
      - ../wpdocker/default.conf:/etc/nginx/conf.d/default.conf
      - ../wpdocker/wordpress.conf:/etc/nginx/global/wordpress.conf
      - ../wpdocker/restrictions.conf:/etc/nginx/global/restrictions.conf

  php:
    #image: php:7.2-fpm
    build: ../wpdocker/php
    volumes:
      - .:/code
      - ../wpdocker/opcache-recommended.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini7
      - ../wpdocker/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass1234'
      MYSQL_ROOT_PASSWORD: 'pass1234'
    ports:
      - '3306:3306'
    volumes:
      - ./dev-db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
      - web
    ports:
      - '81:80'
    environment:
      - PHP_UPLOAD_MAX_FILESIZE=100MB
      - PMA_USER=root
      - PMA_PASSWORD=pass1234
      - PMA_ROOT_PASSWORD=pass1234

